apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly3-config
data:
  APP_ENV: "production"
  APP_DEBUG: "false"
  SITE_OWNER: "homelab118@gmail.com"

  DEFAULT_LANGUAGE: "en_US"
  DEFAULT_LOCALE: "equal"
  TZ: "Asia/Kolkata"

  TRUSTED_PROXIES: "**"

  LOG_CHANNEL: "stack"
  APP_LOG_LEVEL: "notice"
  AUDIT_LOG_LEVEL: "emergency"

  DB_CONNECTION: "pgsql"
  DB_HOST: "192.168.1.140"
  DB_PORT: "5432"
  DB_DATABASE: "firefly"
  DB_USERNAME: "dbadmin"

  MYSQL_USE_SSL: "false"
  MYSQL_SSL_VERIFY_SERVER_CERT: "true"

  CACHE_DRIVER: "file"
  SESSION_DRIVER: "file"

  COOKIE_PATH: "/"
  COOKIE_DOMAIN: ""
  COOKIE_SECURE: "true"
  COOKIE_SAMESITE: "lax"

  MAIL_MAILER: "log"
  AUTHENTICATION_GUARD: "web"

  DKR_CHECK_SQLITE: "true"

  APP_NAME: "FireflyIII"
  BROADCAST_DRIVER: "log"
  QUEUE_DRIVER: "sync"
  CACHE_PREFIX: "firefly"

  FIREFLY_III_LAYOUT: "v1"

  APP_URL: "https://firefly.homelab118.home"
