services:
  server:
    image: docker.gitea.com/gitea:1.25.3
    container_name: gitea
    env_file:
      - .env
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000:4000"
      - "222:222"
