[reverse_proxy]
reverse-proxy ansible_host=192.168.1.122

[databases]
database ansible_host=192.168.1.140

[applications]
streaming ansible_host=192.168.1.130
server-docker ansible_host=192.168.1.131

[bastion_vault]
bastion ansible_host=192.168.1.153

[dns]
dns-server ansible_host=192.168.1.120

[gitea_server]
gitea ansible_host=192.168.1.152
