apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: observability
data:
  datasources.yaml: |
    apiVersion: 1

    deleteDatasources:
      - name: Prometheus
        orgId: 1
      - name: Loki
        orgId: 1

    datasources:
      - name: Prometheus
        uid: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:9090
        isDefault: true
        editable: true

  grafana.ini: |
    [database]
    type = postgres
    host = 192.168.1.140
    name = grafana
    user = dbadmin
    password = $__env{GF_DATABASE_PASSWORD}
