services:
  wud:
    image: getwud/wud:1.0
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    env_file:
      - .env
    labels:
      - wud.watch=true
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.trigger.include=dockercompose.auto
    networks:
      - proxy

networks:
  proxy:
    external: true
