---
- name: Configure Database Servers
  hosts: databases
  become: yes
  pre_tasks:
    - name: Fix locale
      ansible.builtin.import_tasks: ../tasks/fix-locale.yml

    - name: Update and upgrade system
      ansible.builtin.import_tasks: ../tasks/update-upgrade.yml

    - name: Enable unattended upgrades
      ansible.builtin.import_tasks: ../tasks/enable-unattended-upgrades.yml
  roles:
    - postgres
    - mongodb
    - backup
