---
- name: Install Technitium DNS Server
  hosts: dns
  gather_facts: true
  pre_tasks:
    - name: Fix locale
      ansible.builtin.import_tasks: ../tasks/fix-locale.yml

    - name: Update and upgrade system
      ansible.builtin.import_tasks: ../tasks/update-upgrade.yml

    - name: Enable unattended upgrades
      ansible.builtin.import_tasks: ../tasks/enable-unattended-upgrades.yml
  roles:
    - technitium
