apiVersion: v1
kind: Service
metadata:
  name: asap-client
spec:
  selector:
    app: asap-client
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
