apiVersion: v1
kind: Service
metadata:
  name: asap-server
spec:
  selector:
    app: asap-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30004
  type: NodePort
