services:
  vert:
    container_name: vert
    image: ghcr.io/vert-sh/vert:latest
    build:
      context: .
      args:
        PUB_HOSTNAME: ${PUB_HOSTNAME}
        PUB_PLAUSIBLE_URL: ${PUB_PLAUSIBLE_URL}
        PUB_ENV: ${PUB_ENV}
        PUB_DISABLE_ALL_EXTERNAL_REQUESTS: ${PUB_DISABLE_ALL_EXTERNAL_REQUESTS}
        PUB_VERTD_URL: ${PUB_VERTD_URL}
        PUB_DONATION_URL: ${PUB_DONATION_URL}
        PUB_STRIPE_KEY: ${PUB_STRIPE_KEY}
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${PORT:-3080}:80
